server:
  port: 8080

spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      jdbc.lob.non_contextual_creation: true

  datasource:
    url: jdbc:mysql://localhost:3306/translator
    username: root
    password: upiver88
    driver-class-name: com.mysql.cj.jdbc.Driver
